=== Aleren97/TiendaTecnologiaXML/estructura.dtd
<!ELEMENT tecnologia (item+)>

<!ELEMENT item (nombre, marca, precio, stock)>

<!ATTLIST item id CDATA #REQUIRED>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT marca (#PCDATA)>

<!ELEMENT precio (#PCDATA)>

<!ELEMENT stock (#PCDATA)>

=== Aleren97/TiendaTecnologiaXML/datos.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE biblioteca SYSTEM "estructura.dtd">

<tecnologia>

    <item id="item1">

        <nombre>Teclado</nombre>
        <marca>Ryzen</marca>
        <precio>49.99</precio>

    </item>
    
    <item id="item2">
    
        <nombre>Mouse</nombre>
        <marca>Tempest</marca>
        <precio>25.50</precio>
    
    </item>

    <item id="item3">
    
        <nombre>Monitor</nombre>
        <marca>AMD</marca>
        <precio>89.69</precio>
    
    </item>

    <item id="item4">
    
        <nombre>RAM 32GB</nombre>
        <marca>Corsair</marca>
        <precio>300</precio>
    
    </item>

    <item id="item5">
    
        <nombre>Procesador</nombre>
        <marca>AMD</marca>
        <precio>499.95</precio>
    
    </item>

    <item id="item6">
    
        <nombre>Mousepad XL</nombre>
        <marca>Marvel</marca>
        <precio>39.99</precio>
    
    </item>

</tecnologia>
